version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: super_secret
  www:
    build: .
    tty: true
    stdin_open: true
    command: "php -S 0.0.0.0:8087 -t /var/www/"
    ports:
      - "8087:8087"
    volumes:
      - ./src:/var/www
    expose:
      - "8087"

