version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "53306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: coin
      MYSQL_USER: coin
      MYSQL_PASSWORD: coin
  www:
    build: .
    tty: true
    stdin_open: true
    command: "php -S 0.0.0.0:8087 -t /var/www/"
    ports:
      - "8087:8087"
    volumes:
      - ./src:/var/www
    expose:
      - "8087"

